<a href="https://colab.research.google.com/github/Mayuri-thatikonda/project2/blob/main/test_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv('test_scores.csv')

In [ ]:
dataset.head()

school school_setting school_type  ...             lunch pretest  posttest
0  ANKYI          Urban  Non-public  ...  Does not qualify    62.0      72.0
1  ANKYI          Urban  Non-public  ...  Does not qualify    66.0      79.0
2  ANKYI          Urban  Non-public  ...  Does not qualify    64.0      76.0
3  ANKYI          Urban  Non-public  ...  Does not qualify    61.0      77.0
4  ANKYI          Urban  Non-public  ...  Does not qualify    64.0      76.0

[5 rows x 11 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   school           2133 non-null   object 
 1   school_setting   2133 non-null   object 
 2   school_type      2133 non-null   object 
 3   classroom        2133 non-null   object 
 4   teaching_method  2133 non-null   object 
 5   n_student        2133 non-null   float64
 6   student_id       2133 non-null   object 
 7   gender           2133 non-null   object 
 8   lunch            2133 non-null   object 
 9   pretest          2133 non-null   float64
 10  posttest         2133 non-null   float64
dtypes: float64(3), object(8)
memory usage: 183.4+ KB


In [ ]:
dataset.describe()

n_student      pretest     posttest
count  2133.000000  2133.000000  2133.000000
mean     22.796531    54.955931    67.102203
std       4.228893    13.563101    13.986789
min      14.000000    22.000000    32.000000
25%      20.000000    44.000000    56.000000
50%      22.000000    56.000000    68.000000
75%      27.000000    65.000000    77.000000
max      31.000000    93.000000   100.000000

In [ ]:
dataset.isnull().sum()

school             0
school_setting     0
school_type        0
classroom          0
teaching_method    0
n_student          0
student_id         0
gender             0
lunch              0
pretest            0
posttest           0
dtype: int64

In [ ]:
dataset['school'].unique()

array(['ANKYI', 'CCAAW', 'CIMBB', 'CUQAM', 'DNQDD', 'FBUMG', 'GJJHK',
       'GOKXL', 'GOOBU', 'IDGFP', 'KFZMY', 'KZKKE', 'LAYPA', 'OJOBU',
       'QOQTS', 'UAGPU', 'UKPGS', 'UUUQX', 'VHDHF', 'VKWQH', 'VVTVA',
       'ZMNYA', 'ZOWMK'], dtype=object)

In [ ]:
dataset.drop(['school','student_id'],axis=1,inplace=True)

In [ ]:
dataset.classroom.nunique()

97

In [ ]:
dataset.nunique()

school_setting      3
school_type         2
classroom          97
teaching_method     2
n_student          18
gender              2
lunch               2
pretest            69
posttest           68
dtype: int64

In [ ]:
dataset.drop(['classroom'],axis=1,inplace=True)

In [ ]:
dataset.head()

school_setting school_type  ... pretest  posttest
0          Urban  Non-public  ...    62.0      72.0
1          Urban  Non-public  ...    66.0      79.0
2          Urban  Non-public  ...    64.0      76.0
3          Urban  Non-public  ...    61.0      77.0
4          Urban  Non-public  ...    64.0      76.0

[5 rows x 8 columns]

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['school_setting'] = le.fit_transform(dataset['school_setting'])
print(dataset)

      school_setting school_type  ... pretest  posttest
0                  2  Non-public  ...    62.0      72.0
1                  2  Non-public  ...    66.0      79.0
2                  2  Non-public  ...    64.0      76.0
3                  2  Non-public  ...    61.0      77.0
4                  2  Non-public  ...    64.0      76.0
...              ...         ...  ...     ...       ...
2128               2      Public  ...    39.0      55.0
2129               2      Public  ...    38.0      46.0
2130               2      Public  ...    45.0      51.0
2131               2      Public  ...    46.0      53.0
2132               2      Public  ...    41.0      48.0

[2133 rows x 8 columns]


In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['school_type'] = le.fit_transform(dataset['school_type'])
print(dataset)

      school_setting  school_type  ... pretest  posttest
0                  2            0  ...    62.0      72.0
1                  2            0  ...    66.0      79.0
2                  2            0  ...    64.0      76.0
3                  2            0  ...    61.0      77.0
4                  2            0  ...    64.0      76.0
...              ...          ...  ...     ...       ...
2128               2            1  ...    39.0      55.0
2129               2            1  ...    38.0      46.0
2130               2            1  ...    45.0      51.0
2131               2            1  ...    46.0      53.0
2132               2            1  ...    41.0      48.0

[2133 rows x 8 columns]


In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['teaching_method'] = le.fit_transform(dataset['teaching_method'])
print(dataset['teaching_method'])

0       1
1       1
2       1
3       1
4       1
       ..
2128    1
2129    1
2130    1
2131    1
2132    1
Name: teaching_method, Length: 2133, dtype: int64


In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['gender'] = le.fit_transform(dataset['gender'])
print(dataset['gender'])

0       0
1       0
2       1
3       0
4       1
       ..
2128    0
2129    0
2130    0
2131    1
2132    1
Name: gender, Length: 2133, dtype: int64


In [56]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['lunch'] = le.fit_transform(dataset['lunch'])
print(dataset['lunch'])

0       0
1       0
2       0
3       0
4       0
       ..
2128    0
2129    1
2130    1
2131    1
2132    1
Name: lunch, Length: 2133, dtype: int64


In [59]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[ 2.  0.  1. ...  0.  0. 62.]
 [ 2.  0.  1. ...  0.  0. 66.]
 [ 2.  0.  1. ...  1.  0. 64.]
 ...
 [ 2.  1.  1. ...  0.  1. 45.]
 [ 2.  1.  1. ...  1.  1. 46.]
 [ 2.  1.  1. ...  1.  1. 41.]]
[72. 79. 76. ... 51. 53. 48.]


In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [61]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
y_pred = regressor.predict(X_test)
print(y_pred)

[ 46.01462726  69.35673098  50.62714591  65.95070409  44.00576421
  91.97476005  74.03646849  71.2689573   41.0939126   42.19798578
  57.52743493  73.44103384  84.8630568   73.35435671  69.98744831
  71.19335793  91.46492333  61.75085245  42.18027192  87.60327543
  83.03961968  52.69620074  79.16878347  84.47795717  59.86336706
  62.11634876  46.79279058  60.7858708   62.10396673  78.35186892
  78.94293479  71.83245577  61.37661266  61.33818544  97.7631985
  42.470257    80.16968989  40.45614507  64.0933146   63.59585991
  81.71757913  48.78344271  90.54241959  59.96783808  53.84380499
  50.25695682  51.69529432  80.89824215  68.27037166  60.86557775
  54.91066707  49.85028685  80.25972646  78.02043105  77.6097104
  74.71551575  50.23818981  54.75992374  62.26068917  76.56052321
  64.72469715  64.20886338  68.29916329  51.85445712  60.82834872
  76.58931484  64.17169125  54.18331301  73.31316512  52.91491628
  81.14105653  84.83576424  43.22365626  72.69296641  54.11213159
  57.1383337

In [64]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

[[ 46.01  48.  ]
 [ 69.36  70.  ]
 [ 50.63  49.  ]
 [ 65.95  69.  ]
 [ 44.01  40.  ]
 [ 91.97  94.  ]
 [ 74.04  70.  ]
 [ 71.27  75.  ]
 [ 41.09  40.  ]
 [ 42.2   42.  ]
 [ 57.53  54.  ]
 [ 73.44  75.  ]
 [ 84.86  93.  ]
 [ 73.35  76.  ]
 [ 69.99  68.  ]
 [ 71.19  69.  ]
 [ 91.46  98.  ]
 [ 61.75  54.  ]
 [ 42.18  53.  ]
 [ 87.6   85.  ]
 [ 83.04  85.  ]
 [ 52.7   56.  ]
 [ 79.17  82.  ]
 [ 84.48  84.  ]
 [ 59.86  59.  ]
 [ 62.12  63.  ]
 [ 46.79  43.  ]
 [ 60.79  57.  ]
 [ 62.1   60.  ]
 [ 78.35  77.  ]
 [ 78.94  79.  ]
 [ 71.83  74.  ]
 [ 61.38  58.  ]
 [ 61.34  62.  ]
 [ 97.76  96.  ]
 [ 42.47  44.  ]
 [ 80.17  84.  ]
 [ 40.46  44.  ]
 [ 64.09  67.  ]
 [ 63.6   57.  ]
 [ 81.72  83.  ]
 [ 48.78  51.  ]
 [ 90.54  94.  ]
 [ 59.97  58.  ]
 [ 53.84  57.  ]
 [ 50.26  49.  ]
 [ 51.7   47.  ]
 [ 80.9   82.  ]
 [ 68.27  70.  ]
 [ 60.87  55.  ]
 [ 54.91  52.  ]
 [ 49.85  47.  ]
 [ 80.26  78.  ]
 [ 78.02  80.  ]
 [ 77.61  81.  ]
 [ 74.72  73.  ]
 [ 50.24  48.  ]
 [ 54.76  51.  ]
 [ 62.26  59. 

0.9467738990757156

In [65]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

[[ 46.1   48.  ]
 [ 66.55  70.  ]
 [ 46.89  49.  ]
 [ 64.35  69.  ]
 [ 38.59  40.  ]
 [ 93.37  94.  ]
 [ 73.83  70.  ]
 [ 73.5   75.  ]
 [ 41.77  40.  ]
 [ 42.4   42.  ]
 [ 56.3   54.  ]
 [ 76.23  75.  ]
 [ 85.7   93.  ]
 [ 76.66  76.  ]
 [ 70.95  68.  ]
 [ 71.63  69.  ]
 [ 93.15  98.  ]
 [ 59.44  54.  ]
 [ 45.54  53.  ]
 [ 84.93  85.  ]
 [ 83.43  85.  ]
 [ 52.3   56.  ]
 [ 79.25  82.  ]
 [ 85.8   84.  ]
 [ 61.53  59.  ]
 [ 66.03  63.  ]
 [ 46.38  43.  ]
 [ 60.1   57.  ]
 [ 66.22  60.  ]
 [ 78.    77.  ]
 [ 80.1   79.  ]
 [ 70.48  74.  ]
 [ 62.23  58.  ]
 [ 62.95  62.  ]
 [ 99.9   96.  ]
 [ 43.5   44.  ]
 [ 78.63  84.  ]
 [ 43.17  44.  ]
 [ 64.9   67.  ]
 [ 59.63  57.  ]
 [ 82.58  83.  ]
 [ 48.1   51.  ]
 [ 93.7   94.  ]
 [ 58.47  58.  ]
 [ 54.86  57.  ]
 [ 48.17  49.  ]
 [ 48.1   47.  ]
 [ 83.75  82.  ]
 [ 67.8   70.  ]
 [ 59.61  55.  ]
 [ 53.6   52.  ]
 [ 50.05  47.  ]
 [ 83.65  78.  ]
 [ 78.38  80.  ]
 [ 79.13  81.  ]
 [ 77.83  73.  ]
 [ 51.    48.  ]
 [ 54.17  51.  ]
 [ 66.37  59. 

0.9443532380878001